FROM amazoncorretto:17
COPY target/CSYE6225-0.0.1-SNAPSHOT.jar app.jar

ENV DB_HOST=$DB_HOST
ENV DB_NAME=$DB_NAME
ENV DB_USERNAME=$DB_USERNAME
ENV DB_PASSWORD=$DB_PASSWORD
EXPOSE 8080
EXPOSE 3306

ENTRYPOINT ["java","-jar","/app.jar"]