

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysqldb:3306/csye6225db?createDatabaseIfNotExist=true
#    url: jdbc:mysql://localhost:3306/csye6225db?createDatabaseIfNotExist=true
    username: root
    password: root
    hikari:
      initialization-fail-timeout: 10000
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
server:
  port: 8080



