

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/csye6225db
    username: ${DB_ROOT:root}
    password: ${DB_PASSWORD:root}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
server:
  port: ${SERVER_PORT:8080}



