# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: HW-1 CI

on:
  push:
    branches:
      - main
      - hw2
  pull_request:
    branches:
      - main
      - hw2

jobs:
  hw2-CI:

    runs-on: ubuntu-latest

#    services:
#      mysql:
#        image: mysql:8.0.21
#        env:
#          MYSQL_ROOT_PASSWORD: root
#          MYSQL_DATABASE: csye6225db
#        ports:
#          - 3306:3306
#        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=5
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

#      - name: Verify csye6250db DB exists
#        run: mysql --host 127.0.0.1 --port 3306 -uroot -proot -e "SHOW DATABASES LIKE 'csye6225db'"
#


      - name: Build with Maven
        run:
          mvn clean install -DskipTests=false

